# inflator.toml syntax documentation: https://github.com/faretek1/inflator#inflator
name = "hashlib"
version = "v0.0.0"
username = "FAReTek1"

[dependencies]
char = "https://github.com/FAReTek1/char"
