# inflator.toml syntax documentation: https://github.com/faretek1/inflator#inflator
name = "hashlib"
version = "v0.0.0"
username = "FAReTek1"

[dependencies]
char = "https://github.com/FAReTek1/char"
base = "https://github.com/FAReTek1/base"
string = "https://github.com/FAReTek1/string"
math = "https://github.com/FAReTek1/math"
bstr = "https://github.com/FAReTek1/bstr"